[Global]
# Global app settings
Console = true
# Threads count for read and write
Threads = 10
# Threads multiplier for processing 1.0 equal all cores/threads
ThredsMult = 1.0
# Export into subfolders
ExportSubf = true
# Global subfolders preffix
# relative path preffix. For example "../Proc" will create a folder Proc in 
# a parent folder to a camera raw images source folder.
PathPrefix = ""
# log level is 0-5, 0 is most verbose
# 0 = trace, 1 = debug, 2 = info, 3 = warning, 4 = error, 5 = fatal
# fatal - 0 = only fatal errors, 
# fatal - 1 = error,
# fatal - 2 = warning, 
# fatal - 3 = info (default), 
# fatal - 4 = debug, 
# fatal - 5 = trace (most outputs)
Verbosity = 3

[Range]
# Range conversion mode
# 0 - Unsigned [0.0 ~ 1.0]
# 1 - Signed [-1.0 ~ 1.0]
# 2 - Signed to Unsigned [-1.0~1.0] -> [0.0~1.0]
# 3 - Unsigned to Signed [0.0~1.0] -> [-1.0~1.0]
RangeMode = 0

[Export]
# Export settings
# FileFormat:
# -1 - Same as input. If input format can't be
#    used for export (for example CameraRAWs) 
#    app will use default 
# 0 - TIFF
# 1 - OpenEXR
# 2 - PNG
# 3 - JPEG
# 4 - JPEG-2000
# 5 - JPEG XL
# 6 - HEIC
# 7 - PPM
DefaultFormat = 3
FileFormat = -1
# Bit depth: 
# -1 - Original
# 0 - uint8 (8bit unsigned int)
# 1 - uint16 (16bit unsigned int)
# 2 - uint32 (64bit unsigned int) !! most file formats have not support 32bit unsigned int
# 3 - uint64 (64bit unsigned int) !! most file formats have not support double precision
# 4 - half (16bit float)
# 5 - float (32bit float)
# 6 - double (64bit float) !! most file formats have not support double precision
DefaultBit = 1
BitDepth = -1
# Quality
# 100 - lossless or best quality
# 0 - worst quality
Quality = 95


[CameraRaw]
# Raw rotation:
# -1 - Auto EXIF
# 0 - Unrotated/Horisontal
# 3 - 180 Horisontal
# 5 - 90 CW Vertical
# 6 - 90 CCW Vertical
RawRotation = -1
# Raw Color Space
# 0 - raw
# 1 - sRGB
# 2 - sRGB-linear (sRGB primaries, but a linear transfer function)
# 3 - Adobe
# 4 - Wide
# 5 - ProPhoto
# 6 - ProPhoto-linear
# 7 - XYZ
# 8 - ACES (only supported by LibRaw >= 0.18)
# 9 - DCI-P3 (LibRaw >= 0.21)
# 10 - Rec2020 (LibRaw >= 0.2)
RawColorSpace = 1
# Demosaic (only some of this methods are available)
# -2 - raw data (Single channel)
# -1 - no demosaic (RGB)
# 0 - linear 
# 1 - VNG
# 2 - PPG
# 3 - AHD (default)
# 4 - DCB
# 5 ~ 10 is not used
# 11 - DHT
# 12 - AAHD (Modified AHD)
Demosaic = 3
# Import Camera RAW in half resolution
half_size = false
# use_auto_wb
# Use automatic white balance obtained after averaging over the entire image.
use_auto_wb = false
# use_camera_wb
# If possible, use the white balance from the camera.
use_camera_wb = true
# use_camera_matrix
# 0: do not use embedded color profile
# 1 (default): use embedded color profile (if present) for DNG files (always); for other files only if use_camera_wb is set;
# 3: use embedded color data (if present) regardless of white balance setting.
use_camera_matrix = 1
# highlight 
# 0-9: Highlight mode (0=clip, 1=unclip, 2=blend, 3+=rebuild).
highlights = 3
# aberrations
# Correction of chromatic aberrations; [red multiplier, blue multiplier].
aberrations = [1.0, 1.0]
#
# Denoise before debayering. Do not recommended to use both wavelet denoising and FBDD noise reduction!
#
# denoise_mode: 0 - disabled, 1 - wavelength, 2 - fbdd, 3 - both
denoise_mode = 1
# threshold
# Use wavelets to erase noise while preserving real detail. The best threshold should be somewhere between 100 and 1000.
dnz_threshold = 100.0
# fbdd_noiserd
# Controls FBDD noise reduction before demosaic.
# 0 - do not use FBDD noise reduction
# 1 - light FBDD reduction
# 2 (and more) - full FBDD reduction
fbdd_noiserd = 2
# Exif crop
# -1 - disabled, 0 - auto, 1 - force
exif_crop = 0

[OCIO]
# OCIO settings
# OCIO config file
# If empty, OpenColorIO library will use $OCIO environment variable
# If $OCIO is not set, app will give an error
OCIO_Config = "aces_1.2/config.ocio"

[Transform]
# Transform image
# LUT transform mode
# LUT mode: -1 - disabled, 0 - Smart (file path/name), 1 - Force
LutTransform = 0
# Force/Default preset
LutDefault = "_linear"
# Per camera model presets
exif_lut = true

[LUT_Preset]
# Presets
# For relative path the root folder is a OCIO_Config path
_linear = "../../LUTs/test.csp"
_texture = "../../LUTs/test.csp"
_geometry = "../../LUTs/test.csp"
_cross = "../../LUTs/test.csp"
_parallel = "../../LUTs/test.csp"

[Unsharp]
# Unsharp mask
# Unsharp mode: -1 - disabled, 0 - smart, 1 - Force
sharp_mode = 1
# Unsharp kernel
# 0 - gaussian (default), 1 - sharp-gaussian, 2 - box, 3- triangle
# 4 - blackman-harris, 5 - mitchell, 6 - b-spline, 7 - catmull-rom
# 8 - lanczos3, 9 - disk, 10 - binomial, 11 - laplacian, 12 - median
sharp_kernel = 0
sharp_width = 3.0
sharp_contrast = 0.5
sharp_treshold = 0.125